/*
 * libzhreplay — Zero Hour replay file parser implementation
 *
 * This project is not affiliated with or endorsed by Electronic Arts.
 * Command & Conquer is a trademark of Electronic Arts.
 * You must own the original game to use this software.
 *
 * Format reference: docs/REPLAY_FORMAT.md
 * Source of truth: GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
 */

#include "zhreplay.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* -------------------------------------------------------------------------
 * Internal state
 * ---------------------------------------------------------------------- */
struct ZHReplay {
    FILE          *fp;
    char           path[4096];
    int            valid;
    ZHReplayError  error;
    ZHReplayHeader header;
    long           commands_start;  /* file offset where command stream begins */
};

/* -------------------------------------------------------------------------
 * Internal helpers
 * ---------------------------------------------------------------------- */

/* Read exactly n bytes; returns 0 on success, -1 on EOF/error */
static int zh_read(FILE *fp, void *buf, size_t n)
{
    if (fread(buf, 1, n, fp) != n)
        return -1;
    return 0;
}

/*
 * Read a null-terminated UTF-16LE string into dst (UTF-8 output, max dst_len).
 * Engine writes wchar_t strings with fwprintf + fputwc(0).
 * We read wchar_t pairs until we hit a 0x0000 terminator.
 * Non-BMP characters are transliterated to '?'.
 */
static int zh_read_unicode_string(FILE *fp, char *dst, size_t dst_len)
{
    size_t out = 0;
    dst[0] = '\0';
    for (;;) {
        uint16_t wc;
        if (fread(&wc, 2, 1, fp) != 1)
            return -1;
        if (wc == 0)
            break;
        /* Simple ASCII passthrough; non-ASCII becomes '?' */
        if (out + 2 < dst_len) {
            if (wc < 0x80) {
                dst[out++] = (char)(wc & 0x7f);
            } else if (wc < 0x800) {
                dst[out++] = (char)(0xC0 | ((wc >> 6) & 0x1F));
                dst[out++] = (char)(0x80 | (wc & 0x3F));
            } else {
                dst[out++] = (char)(0xE0 | ((wc >> 12) & 0x0F));
                if (out + 1 < dst_len) dst[out++] = (char)(0x80 | ((wc >> 6) & 0x3F));
                if (out + 1 < dst_len) dst[out++] = (char)(0x80 | (wc & 0x3F));
            }
        }
    }
    if (out < dst_len)
        dst[out] = '\0';
    return 0;
}

/*
 * Read a null-terminated ASCII string into dst (max dst_len including null).
 */
static int zh_read_ascii_string(FILE *fp, char *dst, size_t dst_len)
{
    size_t i = 0;
    for (;;) {
        int c = fgetc(fp);
        if (c == EOF)
            return -1;
        if (c == '\0')
            break;
        if (i + 1 < dst_len)
            dst[i++] = (char)c;
    }
    if (i < dst_len)
        dst[i] = '\0';
    return 0;
}

/*
 * Parse the GameInfo ASCII string to extract player data into header.
 * The GameInfo string format is documented in GameInfo.cpp. We extract
 * player names, factions, and slot numbers using a best-effort scan.
 *
 * The format produced by GameInfoToAsciiString() is a semicolon-separated
 * list of key=value pairs. Known keys relevant here:
 *   S[n]=<slot-info>  where n is 0..7
 * Rather than fully parsing the undocumented format, we extract what we can.
 */
static void zh_parse_game_info(ZHReplayHeader *h)
{
    /* Count non-empty slot entries as a proxy for player count.
     * Full GameInfo parsing requires matching GameInfo.cpp exactly. */
    h->num_players = 0;

    /* Scan for S0= through S7= patterns */
    for (int slot = 0; slot < ZH_MAX_PLAYERS; ++slot) {
        char key[8];
        snprintf(key, sizeof(key), "S%d=", slot);
        const char *found = strstr(h->game_options, key);
        if (found) {
            /* Mark slot as present; detailed parsing deferred to full impl */
            h->players[slot].slot = slot;
            h->num_players = slot + 1;
        }
    }
}

/* -------------------------------------------------------------------------
 * Parse header — the meat of the library
 * ---------------------------------------------------------------------- */
static ZHReplayError zh_parse_header(ZHReplay *r)
{
    ZHReplayHeader *h = &r->header;
    FILE *fp = r->fp;

    /* 1. Magic */
    char magic[7] = {0};
    if (zh_read(fp, magic, 6) != 0)
        return ZH_ERR_TRUNCATED;
    if (strncmp(magic, "GENREP", 6) != 0)
        return ZH_ERR_MAGIC;

    /* 2. Stats header
     * The engine uses sizeof(time_t) which is 4 on Win32 and 8 on Win64.
     * Replay files are generated by a Win32 build, so we read 4-byte time_t.
     * We store as int64_t for forward-compat. */
    {
        int32_t t_start = 0, t_end = 0;
        if (zh_read(fp, &t_start, 4) != 0) return ZH_ERR_TRUNCATED;
        if (zh_read(fp, &t_end,   4) != 0) return ZH_ERR_TRUNCATED;
        h->start_time_unix = t_start;
        h->end_time_unix   = t_end;
    }

    if (zh_read(fp, &h->frame_duration, 4) != 0) return ZH_ERR_TRUNCATED;

    /* Bool is typedef int (4 bytes) in the engine */
    {
        int32_t b;
        if (zh_read(fp, &b, 4) != 0) return ZH_ERR_TRUNCATED;
        h->desync_detected = b;
        if (zh_read(fp, &b, 4) != 0) return ZH_ERR_TRUNCATED;
        h->quit_early = b;
        for (int i = 0; i < ZH_MAX_PLAYERS; ++i) {
            if (zh_read(fp, &b, 4) != 0) return ZH_ERR_TRUNCATED;
            h->player_disconnected[i] = b;
        }
    }

    /* 3. Metadata */
    /* Replay name (UTF-16LE, ignored but consumed) */
    char tmp_name[512];
    if (zh_read_unicode_string(fp, tmp_name, sizeof(tmp_name)) != 0)
        return ZH_ERR_TRUNCATED;

    /* SYSTEMTIME: 8 × uint16_t (year, month, dayofweek, day, hour, min, sec, ms) */
    {
        uint16_t st[8];
        if (zh_read(fp, st, sizeof(st)) != 0) return ZH_ERR_TRUNCATED;
        h->date_year   = st[0];
        h->date_month  = st[1];
        /* st[2] = day of week (skip) */
        h->date_day    = st[3];
        h->time_hour   = st[4];
        h->time_minute = st[5];
        h->time_second = st[6];
    }

    /* Version strings */
    if (zh_read_unicode_string(fp, h->version_string, sizeof(h->version_string)) != 0)
        return ZH_ERR_TRUNCATED;
    if (zh_read_unicode_string(fp, h->version_time_string, sizeof(h->version_time_string)) != 0)
        return ZH_ERR_TRUNCATED;
    if (zh_read(fp, &h->version_number, 4) != 0) return ZH_ERR_TRUNCATED;
    if (zh_read(fp, &h->exe_crc,        4) != 0) return ZH_ERR_TRUNCATED;
    if (zh_read(fp, &h->ini_crc,        4) != 0) return ZH_ERR_TRUNCATED;

    /* 4. Game options (ASCII null-terminated) */
    if (zh_read_ascii_string(fp, h->game_options, sizeof(h->game_options)) != 0)
        return ZH_ERR_TRUNCATED;

    /* Local player index (ASCII decimal null-terminated) */
    {
        char idx_str[16];
        if (zh_read_ascii_string(fp, idx_str, sizeof(idx_str)) != 0)
            return ZH_ERR_TRUNCATED;
        h->local_player_index = atoi(idx_str);
    }

    /* 5. Game settings */
    if (zh_read(fp, &h->difficulty,   4) != 0) return ZH_ERR_TRUNCATED;
    if (zh_read(fp, &h->game_mode,    4) != 0) return ZH_ERR_TRUNCATED;
    if (zh_read(fp, &h->rank_points,  4) != 0) return ZH_ERR_TRUNCATED;
    if (zh_read(fp, &h->max_fps,      4) != 0) return ZH_ERR_TRUNCATED;

    /* Parse player info from game_options */
    zh_parse_game_info(h);

    /* Mark command stream start */
    r->commands_start = ftell(fp);
    h->valid = 1;
    return ZH_OK;
}

/* -------------------------------------------------------------------------
 * Public API
 * ---------------------------------------------------------------------- */

ZHReplay *zh_replay_open(const char *path)
{
    if (path == NULL)
        return NULL;

    ZHReplay *r = (ZHReplay *)calloc(1, sizeof(ZHReplay));
    if (r == NULL)
        return NULL;

    strncpy(r->path, path, sizeof(r->path) - 1);
    r->fp = fopen(path, "rb");
    if (r->fp == NULL) {
        r->error = ZH_ERR_IO;
        r->valid = 0;
        return r;
    }

    ZHReplayError err = zh_parse_header(r);
    if (err != ZH_OK) {
        r->error = err;
        r->valid = 0;
        fclose(r->fp);
        r->fp = NULL;
    } else {
        r->error = ZH_OK;
        r->valid = 1;
    }
    return r;
}

int zh_replay_valid(const ZHReplay *r)
{
    return (r != NULL && r->valid);
}

ZHReplayError zh_replay_error(const ZHReplay *r)
{
    if (r == NULL) return ZH_ERR_NULL;
    return r->error;
}

ZHReplayError zh_replay_header(const ZHReplay *r, ZHReplayHeader *header_out)
{
    if (r == NULL || header_out == NULL) return ZH_ERR_NULL;
    *header_out = r->header;
    return ZH_OK;
}

ZHReplayError zh_replay_next_command(ZHReplay *r, ZHCommand *cmd_out)
{
    if (r == NULL || cmd_out == NULL) return ZH_ERR_NULL;
    if (r->fp == NULL) return ZH_ERR_IO;

    memset(cmd_out, 0, sizeof(*cmd_out));

    /* frame, type, playerIndex (4 bytes each) */
    if (fread(&cmd_out->frame,        4, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
    if (fread(&cmd_out->type,         4, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
    if (fread(&cmd_out->player_index, 4, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;

    /* numTypes (1 byte) */
    uint8_t num_types = 0;
    if (fread(&num_types, 1, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;

    /* Type descriptor pairs: (argType u8, argCount u8) × num_types */
    uint8_t arg_types[256];
    uint8_t arg_counts[256];
    if (num_types > 255) return ZH_ERR_PARSE;

    for (int i = 0; i < (int)num_types; ++i) {
        if (fread(&arg_types[i],  1, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
        if (fread(&arg_counts[i], 1, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
    }

    /* Read arguments */
    int arg_idx = 0;
    for (int t = 0; t < (int)num_types; ++t) {
        ZHArgType atype = (ZHArgType)(arg_types[t]);
        int count = (int)(arg_counts[t]);
        for (int k = 0; k < count; ++k) {
            ZHArg arg;
            arg.type = atype;
            memset(&arg.value, 0, sizeof(arg.value));

            switch (atype) {
            case ZH_ARG_INTEGER:
            case ZH_ARG_BOOLEAN:
                if (fread(&arg.value.integer, 4, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
                break;
            case ZH_ARG_REAL:
                if (fread(&arg.value.real, 4, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
                break;
            case ZH_ARG_OBJECTID:
            case ZH_ARG_DRAWABLEID:
            case ZH_ARG_TEAMID:
            case ZH_ARG_TIMESTAMP:
                if (fread(&arg.value.object_id, 4, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
                break;
            case ZH_ARG_LOCATION:
                if (fread(&arg.value.location, sizeof(ZHCoord3D), 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
                break;
            case ZH_ARG_PIXEL:
                if (fread(&arg.value.pixel, sizeof(ZHICoord2D), 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
                break;
            case ZH_ARG_PIXELREGION:
                if (fread(&arg.value.pixel_region, sizeof(ZHIRegion2D), 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
                break;
            case ZH_ARG_WIDECHAR:
                if (fread(&arg.value.wide_char, 2, 1, r->fp) != 1) return ZH_ERR_TRUNCATED;
                break;
            default:
                /* unknown type — we can't determine size, stop parsing this command */
                return ZH_ERR_PARSE;
            }

            if (arg_idx < ZH_MAX_ARGS)
                cmd_out->args[arg_idx++] = arg;
        }
    }
    cmd_out->num_args = arg_idx;
    return ZH_OK;
}

ZHReplayError zh_replay_rewind(ZHReplay *r)
{
    if (r == NULL) return ZH_ERR_NULL;
    if (r->fp == NULL || !r->valid) return ZH_ERR_IO;
    if (fseek(r->fp, r->commands_start, SEEK_SET) != 0)
        return ZH_ERR_IO;
    return ZH_OK;
}

void zh_replay_close(ZHReplay *r)
{
    if (r == NULL) return;
    if (r->fp != NULL) {
        fclose(r->fp);
        r->fp = NULL;
    }
    free(r);
}

const char *zh_replay_error_string(ZHReplayError err)
{
    switch (err) {
    case ZH_OK:            return "OK";
    case ZH_ERR_NULL:      return "null argument";
    case ZH_ERR_IO:        return "file I/O error";
    case ZH_ERR_MAGIC:     return "not a GENREP replay file";
    case ZH_ERR_TRUNCATED: return "file truncated / unexpected end of file";
    case ZH_ERR_PARSE:     return "malformed replay data";
    case ZH_ERR_VERSION:   return "unsupported replay format version";
    default:               return "unknown error";
    }
}
